# Generated by Django 4.0.2 on 2022-02-26 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catapi', '0002_remove_breedurls_id_breedurls_breed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breedurls',
            old_name='breed',
            new_name='breedid',
        ),
    ]
