# Generated by Django 4.0.2 on 2022-02-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapi', '0004_categoryurls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breedurls',
            name='url0',
        ),
        migrations.RemoveField(
            model_name='breedurls',
            name='url1',
        ),
        migrations.RemoveField(
            model_name='breedurls',
            name='url2',
        ),
        migrations.AddField(
            model_name='breedurls',
            name='urls',
            field=models.URLField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
