# Generated by Django 4.0.2 on 2022-02-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapi', '0006_alter_breedurls_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breedurls',
            name='urls',
        ),
        migrations.AddField(
            model_name='breedurls',
            name='url0',
            field=models.JSONField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breedurls',
            name='url1',
            field=models.URLField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breedurls',
            name='url2',
            field=models.URLField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
